### ISSUE TITLE
Lägg till konsekvent datumhantering med paketet `datetime2`

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/dsekdocs#13]
I och med att vi använder oss av `polyglossia`-paketet får vi snygga och språkkorrekta formateringar av `\today`, t.ex. "3 juni 2023". Najs.

Däremot är många protokoll som skrivs inte klara dagen mötet hålls, vilket i så fall hindrar sekreteraren från att lätt få ett så snyggt formaterat datum när denne kompilerar protokollet. Inte najs.

Som åtgärd kan man använda sig av `datetime2`-paketet med `useregional` optionen. Då finns det flera kommandon för att printa datum på olika sätt. Vi kanske kan skapa ett najs kommando som wrappar något av dem för enkelhetens skull.

**Comment by fnurkla** [comment]
Kanske `\isodate{YYYY-MM-DD}` skulle fungera?

**Comment by alfredgrip** [comment]
Idén om att wrappa tycker jag är bra! Skulle isåfall säga `\date{YYYY-MM-DD}` eftersom vi vill syfta på ett *datum* och inte en *dag*. Skulle den isåfall wrappa `\DTMdate{YYYY-MM-DD}` eller har du något annat i åtanke? 

Alternativt delar vi upp det så att vår wrapper tar ett obligatoriskt argument för dag, ett obligatoriskt för månad och ett frivilligt för år, för ibland kanske det är en överdrift att även visa året. Alltså. \date{DD}{MM}[YYYY].

**Comment by fnurkla** [comment]
> Idén om att wrappa tycker jag är bra! Skulle isåfall säga `\date{YYYY-MM-DD}` eftersom vi vill syfta på ett _datum_ och inte en _dag_.
Enda anledningen jag undvek just `\date` var för att det redan finns ett kommando som heter så i LaTeX självt som [vi använder *i* `\setdate`](https://github.com/Dsek-LTH/dsekdocs/blob/2968f783f2aee2909af47cf48632a414be4f1026/dsekdoc.cls#L121C1-L124C2). 

>  Skulle den isåfall wrappa `\DTMdate{YYYY-MM-DD}` eller har du något annat i åtanke?
Det var nog det jag tänkte när jag skapade issuen, men jag är öppen för förslag. 

> Alternativt delar vi upp det så att vår wrapper tar ett obligatoriskt argument för dag, ett obligatoriskt för månad och ett frivilligt för år, för ibland kanske det är en överdrift att även visa året. Alltså. \date{DD}{MM}[YYYY].
Hmm. Det kanske är en idé.

**Comment by fnurkla** [comment]
Så i #29 har jag skapat en enkel implementation. Där kan man skriva `\datum[2024]{01}{21}` för ett datum med år och `\datum{01}{21}` för ett datum utan år.
