### ISSUE TITLE
Coverpage vs maketitle

### ISSUE THREAD

**Issue by kar-re** [Dsek-LTH/dsekdocs#3]
Hej!
Vill börja med att visa min uppskattning för att denna klass finns och det arbete som redan har lagts på det - tack! 😃 

Jag satt med det idag och märkte att `\maketitle` inte var det jag tänkte, utan att det var `\coverpage` jag letade efter. Finns det någon anledning bakom detta beslut? Hur fungerar andra latex-klasser?

Mvh,
Kaspian

**Comment by fnurkla** [comment]
Hmm. Jag har tänkt lite på det här och kommit fram till att den bästa lösningen nog är att ha `\maketitle` agera som `\coverpage` om man inte ger paketet en option som explicit särar på dem (det kanske kan heta `unbind-maketitle` eller så).

**Comment by fnurkla** [comment]
Jag har skapat ett draft för en implementation i #8.

**Comment by fnurkla** [comment]
Mergade just #8, så stänger nu!

**Comment by kar-re** [comment]
Snyggt jobbat! :)
Bra lösning
