### ISSUE TITLE
Contribution guide och projektledning

### ISSUE THREAD

**Issue by kar-re** [Dsek-LTH/dsekdocs#4]
I'm back at it again!

Har @fnurkla några tankar gällande best practice att contributa? Tänker att en contribution guide eller någon form av kanban-board med saker att lägga till skulle vara toppen. Alternativt att issues läggs upp här så att det blir enkelt att plocka tasks. Jag vet inte om det tidigare dsek-paketet kan agera som någon form av riktlinje för vad som finns kvar? 

Tankar? Idéer?

**Comment by fnurkla** [comment]
Jag har lagt till en paragraf i README:n om hur man can contributa i 9645936.

**Comment by fnurkla** [comment]
Är det något mer du saknar @kar-re, annars tänker jag stänger.
