### ISSUE TITLE
Exempelsamling

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/dsekdocs#6]
Är det en bra idé att införa en slags cookbook som innehåller exempel för vanligt förekommande dokumenttyper?

**Comment by fnurkla** [comment]
I #10 lade vi till filen `exampleMotion.tex`. Jag tänker att det då kanske är rimligt att skapa en mapp med flera olika exempel för att illustrera som kan heta cookbook eller examples.

**Comment by alfredgrip** [comment]
Tycker detta är en bra idé, det sänker tröskeln för folk att faktiskt använda paketet och dokumentklasserna, vilket ju är målet med detta. Angående namn på mappen så tycker jag att cookbook är ett kul namn men gillar mer examples (eller templates?)

**Comment by fnurkla** [comment]
Vi har flera exempel nu, men jag tror att de behöver finslipas lite. Efter det kan vi nog stänga det här.

**Comment by fnurkla** [comment]
Okej, jag har förbättrat exemplen nu. De kan nog förbättras ännu mer, men de är nog dugliga för en initial release :)
